title: Just the Docs Template
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://dryewu.github.io/wiki

aux_links:
  Template Repository: https://github.com/dryewu/wiki

plugins:
  - jekyll-default-layout
